name: Workflow ci-test-examen With H2

on: [push,pull_request]

jobs:
   build-on-push:
     if: github.event_name == 'pull-request'
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v4
      - name: print  PR success
        run: echo "pull request successful!"

   print:
     if: github.event_name == 'push'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: print push success
         run: echo "push detected"





