name: Workflow ci-test-examen With H2

on: [push,pull_request]

jobs:
   on-pull-request:
     if: github.event_name == 'pull-request'
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'
      - name: Build with maven
        run: echo "pull request successful!"

   on-push:
     if: github.event_name == 'push'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: print push status
         run: echo "push detected"
# en kommentar
   test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: '17'
       - name: Build and Test
         run: mvn clean test






