name: Workflow ci-test-examen With H2

on: [push,pull_request]

jobs:
   build-and-test:
   on-push:
     if: github.event_name == 'push'
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v4
      - name: print status
        run: echo "push detected"


   on-pull-request:
     if: github.event_name == 'pull-request'
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
               distribution: 'temurin'
               java-version: '17'

      - name: Build and Test with Maven
        run: mvn clean build




